### PR TITLE
Implement rp.logoutRequest()

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Fixes issue #5.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh / @cblakeley - ready for review.

**Comment by cblakeley** [comment]
@dmitrizagidulin: [Commit a78420b](https://github.com/solid/oidc-rp/pull/6/commits/a78420bb25211b74279c0ed85dceab33b286ba00) looks OK to me from the POV of using it from OSDB.
I see that RelyingParty#logout calls RelyingParty#clearSession, whereas the new RelyingParty#logoutRequest doesn't. So, just to be clear, when modifying the caller to replace calls to RelyingParty#logout with RelyingParty#logoutRequest, the caller will now also have to call RelyingParty#clearSession? Thanks.

**Comment by dmitrizagidulin** [comment]
@cblakeley thanks! Yes, you have it right - the new expected behavior is for the calling code to deal with clearing the session separately (like by calling `rp.clearSession()`, but other options possible).

For a couple of reasons - one, the calling code may want a logout URI without triggering the actual session clearing (such as to hook it up to a logout button or link beforehand). And two, since the RelyingParty is intended to be wrapped for use in various environments (server side, in browser, in Web Workers, etc), the *implementation* of session clearing may be different.

**Comment by cblakeley** [comment]
@dmitrizagidulin: https://github.com/solid/oidc-rp/blob/logout-request/src/RelyingParty.js#L378
Should this assertion be removed and fetch(uri, {method}) called only if the OP exposes an end_session_endpoint? 
Google's OIDC provider doesn't provide an end_session_endpoint: https://accounts.google.com/.well-known/openid-configuration.
(I know this version of oidc-rp only handles OIDC OPs which support dynamic registration, so it can't handle Google's OIDC provider, but still is it right to assume end_session_endpoint is mandatory?)

**Comment by dmitrizagidulin** [comment]
Interesting.. (well-noticed btw). I'm really surprised that Google doesn't provide the `end_session_endpoint`. Because then it leads to developer discussions like [this issue thread](https://github.com/IdentityServer/IdentityServer3/issues/3064) or [this SO thread](https://stackoverflow.com/questions/4202161/google-account-logout-and-redirect). What the hell, Google :)
So it sounds like, from a quick overview of existing solutions, people basically put in a special handler for Google (and Microsoft?), since they're common IdPs but don't play well with the spec.

So, I'm not sure what the right call is, as far as making `end_session_endpoint` mandatory. The spec says it's required (which is why those code checks were in there), but clearly several big players aren't playing along. So I'm fine with removing the requirement check. But the question then arises - so what should be done if there's no end_session_endpoint? Like, what's the default behavior?

You're right, with #5, I'm thinking we should gradually deprecate (and then remove) `logout()` in the `oidc-rp` library (it belongs in the wrappers). So yeah, the responsibility for `clearSession()` is moving to the callers.

**Comment by cblakeley** [comment]
@dmitrizagidulin: An alternative would be to retain logout(), to provide symmetry with login(), but have it just call clearSession() and do no more - but make it clear in the comments that this routine is only for use when the OP doesn't support an end_session_endpoint.

**Comment by dmitrizagidulin** [comment]
Hmm. Could be.. Building on that, what if we have `logoutRequest()` return null when no session endpoint is provided (and the client doesn't know a special-case exception like with Google). 
And then encourage the calling wrapper code to still call `clearSession()` but not do a redirect when the result is null?

**Comment by cblakeley** [comment]
Yes - I'd be in favour of that. Anything that makes end session endpoint optional and that clearSession() should be called.

**Comment by dmitrizagidulin** [comment]
Ok, merging shortly - if anybody else has feedback, lets open a new issue.

**Pull request merged**
